tokenizer:
  data_path: 'data/'
  db_faiss_path: 'vectorstore/db_faiss'
  instructor_embeddings: "hkunlp/instructor-xl"
  text_spliter:
    separator: "\n\n"
    chunk_size: 600
    chunk_overlap: 400
    is_separator: True
llm_cpp:
  model_path: "models/llama_2_13b_q8.gguf"
  query: "What type of sensors does ARTEMIS have?"
  custom_prompt_template: |
      Use the following pieces of information to answer the user's question as a casual conversation.
      Don't cite or mention any references from the text or figures. 
      Context: {context}
      Question: {question}
      Only return helpful and gramatically correct answers below.
      Helpful answer:
  load_llm: 
    n_gpu_layers: -1
    n_batch: 512 # This will tune the speed of processing the answer
    max_tokens: 150
    top_p: 0.9
    repeat_penalty: 4.0
    top_k: 10 # 
    n_ctx: 424 
    temperature: 0.4
    verbose: False
    

# How are you feeling today ARTEMIS?
# What type of sensors does ARTEMIS have?