saving_tokens:
  data_path: '../data/'
  db_faiss_path: '../vectorstore/db_faiss'
  text_spliter:
    separator: "\n\n"
    chunk_size: 1000
    chunk_overlap: 100
    is_separator: False
  instructor_embeddings: "hkunlp/instructor-large"
llm_cpp:
  query: "What sensors does the humanoid robot ARTEMIS have?"
  model_path: "../models/ggml-model-q4_0.gguf"
  load_llm:
    n_gpu_layers: -1
    n_batch: 512
    max_tokens: 150
    top_p: 1
    repeat_penalty: 1.2
    top_k: 50
    n_ctx: 2048
    temperature: 0.75
    verbose: True